POST http://localhost:3000/producttype
Content-Type: application/json

    {
        "name":"Carne"
    }

###

GET http://localhost:3000/producttype

###

GET http://localhost:3000/producttype/11

###

PUT http://localhost:3000/producttype/12
Content-Type: application/json

    {
        "name":"Organico"
        
    }

###

DELETE http://localhost:3000/producttype/11